### ISSUE TITLE
Can't run unittest

### ISSUE THREAD

**Issue by Rads92** [eulerrapp/nx-python#14]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request 

* **Do you want to request a *feature* or report a *bug*?**
I started checking Nx monorepo for Python projects. I created example one following steps from readme. Created example app, added one failing test case and tried to run tests.

* **What is the current behavior?**
`rads@rads:~/Pulpit/python-workspace (master)$ nx test example

> nx run example:test 
Executing command: python3 -m unittest discover -s ./ -p apps/example/src/*test*.py

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
1. Create monorepo
2. Add one app
3. Add failing test case
4. Run unit tests

* **What is the expected behavior?**
`rads@rads:~/Pulpit/python-workspace (master)$ python3 -m unittest discover -s ./apps/example/src -p *test*.py
Error: False is not true
F
======================================================================
FAIL: test_message (test_hello.HelloTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rads/Pulpit/python-workspace/apps/example/src/test_hello.py", line 11, in test_message
    self.assertTrue(False)
AssertionError: False is not true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rads/Pulpit/python-workspace/apps/example/src/test_hello.py", line 14, in test_message
    self.assertTrue(False)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)`

What I spotted that `-p` argument should have only pattern and path to app should be passed to `-s` argument, that works fine in my case. Is it my configuration or is it a bug?

**Comment by alphacentauri82** [comment]
This was resolved with the latest version. Closing. Should you encounter any other problems do let us know!
