### ISSUE TITLE
Unable to start new python project with nx g

### ISSUE THREAD

**Issue by bubthegreat** [eulerrapp/nx-python#2]
* **I'm submitting a ...**
  - [x ] bug report
  - [ ] feature request
  - [ ] support request 

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
Can't resolve the collection for generating a new python app in the monorepo

```
bub@bubs-surface-book-2:/mnt/c/Users/bubth/Development/nrwl_test/python-workspace$ npm install -g @nx-python/nx-python  + @nx-python/nx-python@0.1.7
updated 1 package in 0.169s
bub@bubs-surface-book-2:/mnt/c/Users/bubth/Development/nrwl_test/python-workspace$ nx g @nx-python/nx-python:app my-python-backend
Collection "@nx-python/nx-python" cannot be resolved.
bub@bubs-surface-book-2:/mnt/c/Users/bubth/Development/nrwl_test/python-workspace$     
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
I'd expect the tutorial in the README.md to work

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

Running windows ten insider builds, specifically in WSL2 on ubuntu 20.02

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by superdiana** [comment]
Hey @bubthegreat, apologies for the lack of response.  @melveg  ⭐️   can you take a look at this?

**Comment by jolares** [comment]
having a similar issue

![image](https://user-images.githubusercontent.com/10701446/121780584-0758ca80-cb6f-11eb-9a32-27ba743ab611.png)

**Comment by alphacentauri82** [comment]
Have you used our latest release? @jolares

**Comment by sandangel** [comment]
@alphacentauri82 he has the same issue with mine in #32

**Comment by alphacentauri82** [comment]
Roger. Checking issues after midnight isn't a good idea. Apologies for the inconveniences! fixing

**Comment by alphacentauri82** [comment]
https://www.npmjs.com/package/@nx-python/nx-python - Fixed!!

**Comment by jolares** [comment]
Thank you! I just tested it and it works well. 

The flask schematic seems  not to be adding the  project within  within apps/ directory btw. The django and default schematics are working well, but the flask one only adds the project to the workspace.json; haven't tested yet with an workspace preset to angular (with angular.json)

**Comment by anfibiacreativa** [comment]
We will take a look, asap. Thanks for reporting.
