### ISSUE TITLE
published wrong folder

### ISSUE THREAD

**Issue by sandangel** [eulerrapp/nx-python#32]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request 

* **Do you want to request a *feature* or report a *bug*?**
The latest version was published without building the plugin and publish the dist folder

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by alphacentauri82** [comment]
This isn't a bug report but advertising a service? Closing.

**Comment by sandangel** [comment]
@alphacentauri82 
> The latest version was published without building the plugin and publish the dist folder

please check the installed package in node_modules, you will understand what I mean.

**Comment by alphacentauri82** [comment]
Roger. I noticed! fixing
